[project]
name = "messier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adjusttext>=1.3.0",
    "astropy>=7.2.0",
    "astroquery>=0.4.7",
    "matplotlib>=3.10.0",
]
